# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izwFR-h1b3S0IJ2h9Exo1_YtMH4v5TZa
"""

class BankAccount:
    def __init__(self, account_number, initial_balance, owner_name):
        self.__account_number = account_number
        self.__balance = initial_balance
        self.__owner_name = owner_name

    def deposit(self, amount):
        """Add funds to the account."""
        if amount > 0:
            self.__balance += amount
            print(f"Deposited {amount} into account {self.__account_number}")
        else:
            print("Invalid deposit amount.")

    def withdraw(self, amount):
        """Withdraw funds from the account."""
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrew {amount} from account {self.__account_number}")
        else:
            print("Insufficient funds or invalid withdrawal amount.")

    def get_balance(self):
        """Get the current balance."""
        return self.__balance

    def get_owner_name(self):
        """Get the owner's name."""
        return self.__owner_name

# Example Usage:
account1 = BankAccount("123456789", 1000, "rajveer singh")
print("Owner:", account1.get_owner_name())
print("Initial Balance:", account1.get_balance())
account1.deposit(500)
print("Current Balance:", account1.get_balance())
account1.withdraw(200)
print("Current Balance after withdrawal:", account1.get_balance())