# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyR2urBWDTPRX5JCvU7ZC-xxO8P5dxlF
"""

a code in python to show all levels of inheritance
# Base class
class Animal:
    def __init__(self, species):
        self.species = species

    def speak(self):
        return f"I am a {self.species}."

# Intermediate level class
class Mammal(Animal):
    def __init__(self, species, sound):
        super().__init__(species)
        self.sound = sound

    def speak(self):
        return f"I am a {self.species} mammal and I say {self.sound}."

# Derived class
class Dog(Mammal):
    def __init__(self, breed):
        super().__init__("dog", "woof")
        self.breed = breed

    def speak(self):
        return f"I am a {self.breed} dog and I say {self.sound}."

# Further derived class
class Poodle(Dog):
    def __init__(self):
        super().__init__("Poodle")

    def speak(self):
        return f"I am a Poodle and I say {self.sound}."

# Creating instances and demonstrating inheritance
animal = Animal("unknown")
print(animal.speak())  # I am a unknown.

mammal = Mammal("tiger", "roar")
print(mammal.speak())  # I am a tiger mammal and I say roar.

dog = Dog("Labrador")
print(dog.speak())  # I am a Labrador dog and I say woof.

poodle = Poodle()
print(poodle.speak())  # I am a Poodle and I say woof.

a code of Method Overloading


class Calculator:
    def add(self, a, b=0, c=0):
        return a + b + c

# Creating an instance of Calculator
calc = Calculator()

# Example of method overloading using default parameter values
print(calc.add(1))          # Output: 1
print(calc.add(1, 2))       # Output: 3
print(calc.add(1, 2, 3))    # Output: 6

a code of Method Overriding
# Base class
class Animal:
    def speak(self):
        return "Generic animal sound"

# Derived class overriding method
class Dog(Animal):
    def speak(self):
        return "Woof!"

# Derived class overriding method
class Cat(Animal):
    def speak(self):
        return "Meow!"

# Derived class not overriding method
class Cow(Animal):
    pass

# Creating instances and calling overridden methods
animal = Animal()
dog = Dog()
cat = Cat()
cow = Cow()

print(animal.speak())  # Output: Generic animal sound
print(dog.speak())     # Output: Woof!
print(cat.speak())     # Output: Meow!
print(cow.speak())     # Output: Generic animal sound