# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRiNof9zC-TlFma33Uo0331TQIBh8cCo
"""

age = input("Enter your age:")
age = int(age)
if age >=18:
  print("Your are an adult.")
else:
  print("You are a minor.")

score = input("Enter your score: ")
score = int(score)
if (score > 100 or score < 0):
    print("invalid score!")
elif score >= 95:
    print("Grade: A*")
elif score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: A-")
elif score >= 70:
    print("Grade: B")
elif score >= 60:
    print("Grade: B-")
elif score >= 50:
    print("Grade: C")
else:
  print("Grade: F")

num = input("Enter any number: ")
num = int(num)

if (num % 2) == 0:
    print(f"{num} is even.")
else:
    if (num % 5) == 0:
        print(f"{num} is odd and divisible by 5.")
    else:
        print(f"{num} is odd and not divisible by 5.")

def factorial(num):
  if (num==0 or num==1):
    return 1
  fact = 1
  for x in range(2,(num+1)):
    fact *= x
  return fact
print(factorial(0))
print(factorial(3))
print(factorial(5))

def fibonacci(num):
  if (num<=1):
    return 1
  fib = [1,1]
  for x in range(2,(num+1)):
    temp = fib[-1] + fib[-2]
    fib.append(temp)
  return fib[-1]
print(fibonacci(2))
print(fibonacci(5))
print(fibonacci(6))
print(fibonacci(8))

def isPrime(num):
    if num <= 1:
        return False
    r = num ** 0.5
    for i in range(2, int(r) + 1):
        if num % i == 0:
            return False
    return True


print(isPrime(1))
print(isPrime(2))
print(isPrime(4))
print(isPrime(9))
print(isPrime(107))