# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gHBJ4L-XH_B2NDnIeejxvlb296vSYzR
"""

def display_info(name, age):
  print(f"Name: {name}")
  print(f"Age: {age}")


display_info("Zico", 21)

def print_names(*names):
    for name in names:
      print(name)

print_names("Alice", "Bob", "John", "Harry")

def calculation(num1, num2):
  return ((num1 + num2), (num1 - num2))



result = calculation(70, 80)
print(f"Addition: {result[0]}")
print(f"Subtraction: {result[1]}")

def show_employee(name, salary=67000):
  print(f"Name: {name}")
  print(f"Salary: {salary}")


show_employee("rajveer", 54000)
show_employee("bais")

def outer_func(a,b):
  def inner_func(a, b):
    return a + b
    addition_result = inner_func(a, b)
    final_result = addition_result + 5
    return final_result
print(outer_func(79,56))
print(outer_func(45,78))

def num_sum(num):
  if num == 0:
    return 0
  return num + num_sum(num - 1)
result = num_sum(90)
print(result)

def display_student(name, age):
  print(f"Name: {name}")
  print(f"Age: {age}")
def show_student(name, age):
  display_student(name, age)
display_student("garsion", 37)
show_student("garison", 37)

def even_numbers(start, end):
  return [num for num in range(start, end + 1) if num % 2 == 0]


evens = even_numbers(8,34)
print(evens)

def max_item(nums):
  max_value = nums[0]
  for num in nums:
    if num > max_value:
      max_value = num
  return max_value
my_list = [2, 4, 8, 16, 12, 28]
max_element = max_item(my_list)
print(f"Max Item: {max_element}")